collections:
  - portfolio
  - writing

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - html-proofer
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - working-folder
  - .gitignore
  - gemfile
  - gemfile.lock