collections:
  portfolio:
    output: true
    order: 
      - jekyllrb.md
      - recyclaide.md
      - draying-io.md
      - project-benji.md
      - 2019-03-14-style-guide.md
      - 2019-03-14-data-analysis.md
      - 2018-10-09-thinkrite.md
      - 2017-12-28-miami-schools.md
      - 2017-12-28-wellness.md
      - 2017-12-28-bloombox.md
      - 2017-12-29-before-ux.md

permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - html-proofer
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - working-folder
  - .gitignore
  - gemfile
  - gemfile.lock