collections:
  portfolio:
    output: true
    order: 
      - jekyllrb.md
      - recyclaide.md
      - containerco.md
      - project-ada.md
      - project-benji.md
      - style-guide.md
      - data-analysis.md
      - thinkrite.md
      - miami-schools.md
      - wellness.md
      - bloombox.md
      - before-ux.md

permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - html-proofer
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - working-folder
  - .gitignore
  - gemfile
  - gemfile.lock