collections:
  portfolio:
    output: true
#    order: 
#      - safrapay.md
#      - 2020-02-11-jekyllrb.md
#      - 2020-02-11-recyclaide.md
#      - 2020-02-11-containerco.md
#      - 2020-02-12-project-ada.md
#      - 2020-02-11-project-benji.md
#      - 2019-03-14-style-guide.md
#      - 2019-03-14-data-analysis.md
#      - 2018-10-09-thinkrite.md
#      - 2017-12-28-miami-schools.md
#      - 2017-12-28-wellness.md
#      - 2017-12-28-bloombox.md
#      - 2017-12-29-before-ux.md
  notes:
    output: true
    order:
      - test-two.md
      - 2020-06-26.md
      - test-three.md

permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - html-proofer
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - working-folder
  - .gitignore